### ISSUE TITLE
Encoding issue when opening dump zip file

### ISSUE THREAD

**Issue by BeerboyUK** [thayakawa-gh/SlackLogViewer#22]
I encountered the following error when opening a .zip file:

Traceback (most recent call last):
  File "/Users/mark/.local/bin/slack-export-viewer", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/mark/.local/pipx/venvs/slack-export-viewer/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mark/.local/pipx/venvs/slack-export-viewer/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/mark/.local/pipx/venvs/slack-export-viewer/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mark/.local/pipx/venvs/slack-export-viewer/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mark/.local/pipx/venvs/slack-export-viewer/lib/python3.12/site-packages/slackviewer/main.py", line 79, in main
    configure_app(app, archive, channels, no_sidebar, no_external_references, debug)
  File "/Users/mark/.local/pipx/venvs/slack-export-viewer/lib/python3.12/site-packages/slackviewer/main.py", line 21, in configure_app
    path = extract_archive(archive)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mark/.local/pipx/venvs/slack-export-viewer/lib/python3.12/site-packages/slackviewer/archive.py", line 74, in extract_archive
    info.filename = info.filename.encode("cp437").decode("utf-8")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/encodings/cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u0161' in position 26: character maps to <undefined>
encoding with 'cp437' codec failed

Can you advise on how to resolve the issue? Thank you.

**Comment by thayakawa-gh** [comment]
Is your question for slack-export-viewer, not SlackLogViewer?
